[tool.poetry]
name = "faker-jsonschema"
version = "0.1.0"
description = ""
authors = ["Anentropic <ego@anentropic.com>"]

[tool.poetry.dependencies]
python = "^3.7"
faker = "^4.0.2"
hypothesis = "^5.8.0"
typing_extensions = "^3.7.4"
pytz = "^2019.3"
wrapt = "^1.12.1"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
ipython = "^7.13.0"
ipdb = "^0.13.2"
flaky = "^3.6.1"
hypothesis = "^5.10.4"
pytype = "^2020.4.22"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
